ToIEnumerable
SmartPluginsCommunity/RedButton pull request #13
Opened 2022-04-06 08:48 UTC by andrejjerdna

2022-04-06 12:56 UTC, thearnkey requested changes

2022-04-06 12:56 UTC, thearnkey commented on src/Common/RedButton.Common.TeklaStructures/Extensions/PartExtension.cs
> +        public static IEnumerable<Point> GetOuterContour(this Part part, Point p1, Point p2, Point p3, Solid.SolidCreationTypeEnum solidType)
Добавить перегрузку функции, которая принимает именно Plane для удобства

2022-04-06 13:39 UTC, andrejjerdna commented on src/Common/RedButton.Common.TeklaStructures/Extensions/PartExtension.cs
> +        public static IEnumerable<Point> GetOuterContour(this Part part, Point p1, Point p2, Point p3, Solid.SolidCreationTypeEnum solidType)
А если я так в лоб возьму, должно же вроде заработать? Что-то голова уже не думает сегодня...
public static IEnumerable<IEnumerable<Point>> GetAllContours(this Part part, Plane plane, Solid.SolidCreationTypeEnum solidType)
        {
            return GetIntersections(part.GetSolid(solidType), plane.Origin, plane.AxisX, plane.AxisY);
        }

2022-04-09 08:32 UTC, thearnkey approved these changes

2022-04-09 08:32 UTC, merged