Feature/Properties extractor
SmartPluginsCommunity/RedButton pull request #14
Opened 2022-04-11 06:17 UTC by andrejjerdna

https://trello.com/c/qnPF1mhF

2022-04-11 08:48 UTC, thearnkey requested changes

2022-04-11 08:48 UTC, thearnkey commented on src/Common/RedButton.Common.TeklaStructures/Model/Properties/TeklaPropertyDouble.cs
> +        public TeklaPropertyDouble(string name, double? value)
Если изначально сюда идет null, то есть смысл убрать отсюда double? value; и для value задать сразу значение null, а лучше избавиться вообще от null и использовать тот же double.MinValue; Меньше будет ошибок в дальнейшем

2022-04-11 08:48 UTC, thearnkey commented on src/Common/RedButton.Common.TeklaStructures/Model/Properties/PropertiesExtractor.cs
> +        public TeklaPropertyString AddStringAttribute(string attribute)
добавить метод AddProperty(TeklaPropertyBase property) для добавления конкретного свойства в конвеер.

2022-04-11 08:48 UTC, thearnkey commented on src/Common/RedButton.Common.TeklaStructures/Model/Properties/TeklaPropertyBase.cs
> +    public abstract class TeklaPropertyBase
Добавить **Value** в абстрактный класс.

2022-04-11 08:51 UTC, thearnkey commented on src/Tests/RedButton.Tests.UnitTests/PropertiesTests/PropertiesExtractorTests.cs
> +            var total = properties.AddIntegerAttribute("MODEL_TOTAL");
Этот атрибут разве работает нормально? _Замечал что он работает нормально только в шаблонах._

2022-04-11 13:13 UTC, vadsemenov commented on src/Common/RedButton.Common.Core/CollectionExtensions/EnumerableExtensions.cs
> +        /// <param name="enumerable"></param>
Я про эту строчку:
/// <param name="enumerable"></param>

2022-04-18 07:37 UTC, user5850361 approved these changes

2022-05-02 13:08 UTC, merged